### ISSUE TITLE
Handle multiple callback outputs

### ISSUE THREAD

**Issue by GibbsConsulting** [GibbsConsulting/django-plotly-dash#141]
v0.39 of Dash introduced the ability to return multiple values from a single callback. dpd needs extending to follow this.
The key step is to make sure all values are stored if needed.

Note also that #138, whilst thought to be a separate issue, also pertains to the correct handling of returned values from callbacks.

**Comment by GibbsConsulting** [comment]
Done in #165 thanks to @gianlucasalvato

**Comment by sheepadoodle1** [comment]
I went to follow a 'multiple outputs' example on Dash and I received an error saying that this has not been implemented in django-plotly-dash. Is it done but the release is just in the pipeline?

**Comment by delsim** [comment]
It should be in v0.9.13 - best check what version you have installed. If you do have this version (or later) then it could be a bug.

**Comment by sheepadoodle1** [comment]
Yeah I can see it in dash_wrapper line 457, it says to raise 'not implemented error' if the type is a list. I removed the check but the code still fails, which makes sense as its not expecting a list of outputs in other functions?

**Comment by GibbsConsulting** [comment]
Oopsie, thats my mistake - I confused client side callbacks with multiple callback outputs.
Reopening this issue as the work remains to be done.

**Comment by texnidata** [comment]
This would be a really useful feature. 
If the work remains to be done, is it planned?

**Comment by johnmathews** [comment]
This would be a really useful feature.
If the work remains to be done, is it planned?

**Comment by WLambre** [comment]
Just like to add that I would also appreciate this feature. In terms of a use case, I believe this will allow for fasting loading when a single input has multiple outputs which aren't quite related. Nothing that can't be done already, but it would be faster and with cleaner code.

**Comment by johnmathews** [comment]
Indeed. nothing that can’t be solved with some refactoring. Cleaner code and easier to convert from a normal dash app to a django dash app. Awesome tool, thank you for creating it!

**Comment by oi-eddyoj** [comment]
I'm not convinced this would allow faster apps but I agree about cleaner code. The other main milestone is that it also allows another level of flexibility in the UI e.g. complex modals with multiple buttons or even screens become much easier. This in conjunction with client-side callbacks would make DPD a practical choice in single page app technology.

**Comment by ishto7** [comment]
+1

**Comment by dylancunningham1** [comment]
I have a couple examples where this would be useful:
1. Send dropdown "options" to the options arg and one specific option to the "value" arg. I can't set a default to the "value" arg initially because my downdown options change based on other dropdowns waiting for user input. But, multiple outputs would allow me to set a default to the "value" arg dynamically.
2. My app pulls data from S3 regularly, if I have to pull the same data in multiple callbacks (right now I have a lot!), to use for similar reasons, then my app will slow down the more callbacks I create. However, multiple callbacks would GREATLY speed up my app.

**Comment by eddy-ojb** [comment]
I take back what i said about this not speeding up apps. Im just not sure now. I thought the speed of the apps was fine until i deployed to the cloud. After some painful diagnosis with the Azure team, my apps are complex and chatty with the server which resulted in some poor performance issues, which led me to think the speed of our apps could be increased by reducing the number of callbacks for outputting small bits of data to multiple components

**Comment by scythargon** [comment]
+1
I might be able implement this if you give me any clues where to start from. Thanks.

**Comment by GibbsConsulting** [comment]
Closing this issue as #194 has been merged to master
